"""PDF Maker — turn text/markdown into a beautifully styled PDF via headless Edge.

stdin format:
    TITLE: My Document Title        (optional first line)
    ...markdown-ish body: # / ## headings, **bold**, - bullets, plain paragraphs...

Output: <safe_title>.pdf on the Desktop. No pip packages needed (uses Microsoft
Edge, present on every Windows PC; falls back to reportlab if Edge is missing).
"""
import html
import os
import re
import subprocess
import sys
import tempfile
import time
from pathlib import Path

EDGE_PATHS = [
    r"C:\Program Files (x86)\Microsoft\Edge\Application\msedge.exe",
    r"C:\Program Files\Microsoft\Edge\Application\msedge.exe",
]

CSS = """
@page { margin: 22mm 18mm; }
body { font-family: 'Segoe UI', Arial, sans-serif; color: #1d232b; line-height: 1.65;
       font-size: 11.5pt; max-width: 100%; }
h1 { font-size: 24pt; color: #14315c; border-bottom: 3px solid #2a78d6;
     padding-bottom: 8px; margin: 0 0 6px 0; letter-spacing: 0.3px; }
.subtitle { color: #6b7684; font-size: 10pt; margin-bottom: 26px; }
h2 { font-size: 15pt; color: #1d4e94; margin: 22px 0 8px 0; }
h3 { font-size: 12.5pt; color: #2a5aa0; margin: 16px 0 6px 0; }
p { margin: 0 0 10px 0; text-align: justify; }
ul { margin: 0 0 12px 0; padding-left: 22px; }
li { margin-bottom: 4px; }
strong { color: #14315c; }
blockquote { border-left: 4px solid #2a78d6; margin: 12px 0; padding: 6px 14px;
             background: #f2f6fc; color: #37404b; }
"""


def md_to_html(text: str) -> str:
    out, in_list = [], False

    def close_list():
        nonlocal in_list
        if in_list:
            out.append("</ul>")
            in_list = False

    def inline(s: str) -> str:
        s = html.escape(s)
        return re.sub(r"\*\*(.+?)\*\*", r"<strong>\1</strong>", s)

    for line in text.splitlines():
        line = line.rstrip()
        if not line.strip():
            close_list()
            continue
        if line.startswith("### "):
            close_list(); out.append(f"<h3>{inline(line[4:])}</h3>")
        elif line.startswith("## "):
            close_list(); out.append(f"<h2>{inline(line[3:])}</h2>")
        elif line.startswith("# "):
            close_list(); out.append(f"<h2>{inline(line[2:])}</h2>")
        elif line.startswith("> "):
            close_list(); out.append(f"<blockquote>{inline(line[2:])}</blockquote>")
        elif re.match(r"^\s*[-*] ", line):
            if not in_list:
                out.append("<ul>"); in_list = True
            out.append(f"<li>{inline(re.sub(r'^\\s*[-*] ', '', line))}</li>")
        else:
            close_list(); out.append(f"<p>{inline(line)}</p>")
    close_list()
    return "\n".join(out)


def edge_exe():
    for p in EDGE_PATHS:
        if Path(p).is_file():
            return p
    return None


def reportlab_fallback(title: str, body_text: str, pdf_path: Path) -> bool:
    try:
        from reportlab.lib.pagesizes import A4
        from reportlab.lib.styles import getSampleStyleSheet
        from reportlab.platypus import Paragraph, SimpleDocTemplate, Spacer

        styles = getSampleStyleSheet()
        doc = SimpleDocTemplate(str(pdf_path), pagesize=A4)
        flow = [Paragraph(html.escape(title), styles["Title"]), Spacer(1, 14)]
        for para in body_text.split("\n\n"):
            if para.strip():
                flow.append(Paragraph(html.escape(para.strip()).replace("\n", "<br/>"),
                                      styles["BodyText"]))
                flow.append(Spacer(1, 8))
        doc.build(flow)
        return True
    except Exception as e:
        print(f"reportlab fallback failed: {e}")
        return False


def main():
    raw = sys.stdin.read().strip() if not sys.stdin.isatty() else ""
    if not raw:
        print("PDF Maker ready. Usage: stdin par bhejo —")
        print("  TITLE: Mera Document")
        print("  # Section\\n  content... (**bold**, - bullets, ## headings supported)")
        print("PDF Desktop par save hoga.")
        return

    title = "Maya Document"
    m = re.match(r"^TITLE:\s*(.+)$", raw.splitlines()[0].strip(), re.IGNORECASE)
    if m:
        title = m.group(1).strip()
        raw = "\n".join(raw.splitlines()[1:])

    safe = re.sub(r"[^\w\- ]", "", title).strip().replace(" ", "_")[:60] or "maya_document"
    desktop = Path.home() / "Desktop"
    desktop.mkdir(exist_ok=True)
    pdf_path = desktop / f"{safe}.pdf"

    doc_html = (f"<!DOCTYPE html><html><head><meta charset='utf-8'><style>{CSS}</style></head>"
                f"<body><h1>{html.escape(title)}</h1>"
                f"<div class='subtitle'>Generated by Maya · {time.strftime('%d %b %Y')}</div>"
                f"{md_to_html(raw)}</body></html>")

    exe = edge_exe()
    if exe:
        with tempfile.TemporaryDirectory() as td:
            html_file = Path(td) / "doc.html"
            html_file.write_text(doc_html, encoding="utf-8")
            try:
                subprocess.run(
                    [exe, "--headless", "--disable-gpu", "--no-first-run",
                     f"--print-to-pdf={pdf_path}", html_file.as_uri()],
                    capture_output=True, timeout=25,
                )
            except subprocess.TimeoutExpired:
                pass
        if pdf_path.is_file() and pdf_path.stat().st_size > 500:
            print(f"PDF ban gaya: {pdf_path}")
            return
        print("Edge se PDF nahi bana — reportlab fallback try kar rahi hoon...")

    if reportlab_fallback(title, raw, pdf_path):
        print(f"PDF ban gaya (simple style): {pdf_path}")
    else:
        print("PDF nahi ban paya — na Edge mila na reportlab. Microsoft Edge install karo.")


if __name__ == "__main__":
    try:
        main()
    except Exception as e:
        print(f"PDF maker error: {e}")
